 <?php

 $title = 'Edit Career';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'career',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formHidden($form->get('status'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('total_duration'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
