 <?php

 $title = 'Careers';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('career', array('action'=>'add'));?>">Add new Career</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>Total Duration</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($careers as $career) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($career->name);?></td>
     <td><?php echo $this->escapeHtml($career->total_duration);?></td>
     <td>
         <a href="http://thinkcsi.net/front/application/outlines.php?id=<?php echo $career->id ?>">
             Outlines</a>
         <a href="<?php echo $this->url('career',
             array('action'=>'edit', 'id' => $career->id));?>">Edit</a>
         <a href="<?php echo $this->url('career',
             array('action'=>'delete', 'id' => $career->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>