 <?php

 $title = 'Categories';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('category', array('action'=>'add'));?>">Add new Category</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($categories as $category) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($category->name);?></td>
     <td>
         <a href="<?php echo $this->url('category',
             array('action'=>'edit', 'id' => $category->id));?>">Edit</a>
         <?php
         if (empty($category->default)) {
             if (empty($category->status)) {
         ?>
         <a href="<?php echo $this->url('category',
             array('action'=>'activate', 'id' => $category->id));?>">Activate</a>
         <?php
             } else {
         ?>
         <a href="<?php echo $this->url('category',
             array('action'=>'deactivate', 'id' => $category->id));?>">Deactivate</a>

         <?php
             }
         }
         ?>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>