 <?php

 $title = 'Categories';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('skill', array('action'=>'add'));?>">Add new Skill</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($skills as $skill) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($skill->name);?></td>
     <td>
         <a href="<?php echo $this->url('skill',
             array('action'=>'edit', 'id' => $skill->id));?>">Edit</a>
         <?php
            if (empty($skill->status)) {
         ?>
         <a href="<?php echo $this->url('skill',
             array('action'=>'activate', 'id' => $skill->id));?>">Activate</a>
         <?php
            } else {
         ?>
         <a href="<?php echo $this->url('skill',
             array('action'=>'deactivate', 'id' => $skill->id));?>">Deactivate</a>

         <?php
            }
         ?>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>