 <?php

 $title = 'Categories';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('skill', array('action'=>'add'));?>">Add new Skill</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($categories as $skill) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($skill->name);?></td>
     <td>
         <a href="<?php echo $this->url('skill',
             array('action'=>'edit', 'id' => $skill->id));?>">Edit</a>
         <a href="<?php echo $this->url('skill',
             array('action'=>'delete', 'id' => $skill->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>