 <?php

 $title = 'Courses';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('course', array('action'=>'add'));?>">Add new Course</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>Total Duration</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($courses as $course) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($course->name);?></td>
     <td>
         <a href="<?php echo $this->url('course',
             array('action'=>'edit', 'id' => $course->id));?>">Edit</a>
         <?php
            if (empty($course->status)) {
         ?>
         <a href="<?php echo $this->url('course',
             array('action'=>'activate', 'id' => $course->id));?>">Activate</a>
         <?php
            } else {
         ?>
         <a href="<?php echo $this->url('course',
             array('action'=>'deactivate', 'id' => $course->id));?>">Deactivate</a>

         <?php
            }
         ?>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>